tap "adoptopenjdk/openjdk"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "stripe/stripe-cli"
tap "vitorgalvao/tiny-scripts"
brew "avrdude"
brew "cocoapods"
brew "deno"
brew "pcre2"
brew "fish"
brew "gcc"
brew "gh"
brew "git"
brew "git-flow"
brew "libtasn1"
brew "gnupg"
brew "helm"
brew "libimobiledevice"
brew "ideviceinstaller"
brew "ios-deploy"
brew "jabba"
brew "jenv"
brew "openjdk"
brew "kafka"
brew "kompose"
brew "kubernetes-cli", link: false
brew "libsodium"
brew "mas"
brew "maven"
brew "minikube"
brew "mkcert"
brew "nss", link: false
brew "nvm"
brew "pinentry-mac"
brew "pnpm", link: false
brew "podman"
brew "postgresql", restart_service: true
brew "postgresql@13"
brew "python@3.8"
brew "rover"
brew "ruby"
brew "speedtest-cli"
brew "telnet"
brew "volta"
brew "webp"
brew "heroku/brew/heroku"
brew "stripe/stripe-cli/stripe"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "1password"
cask "adoptopenjdk"
cask "adoptopenjdk12"
cask "android-studio"
cask "battle-net"
cask "brave-browser"
cask "brave-browser-dev"
cask "caldigit-docking-utility"
cask "datagrip"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "figma"
cask "firefox"
cask "flutter"
cask "flux"
cask "github"
cask "gitkraken"
cask "google-chrome"
cask "intellij-idea"
cask "java"
cask "kitematic"
cask "logitech-camera-settings"
cask "logitech-options"
cask "microsoft-edge"
cask "microsoft-teams"
cask "minecraft"
cask "mono-mdk-for-visual-studio"
cask "ngrok"
cask "nordvpn"
cask "notion"
cask "obs"
cask "onedrive"
cask "plasticscm-cloud-edition"
cask "postman"
cask "qbittorrent"
cask "raycast"
cask "react-native-debugger"
cask "sketch"
cask "slack"
cask "spotify"
cask "steam"
cask "unity"
cask "unity-android-support-for-editor"
cask "unity-hub"
cask "unity-ios-support-for-editor"
cask "visual-studio"
cask "visual-studio-code"
cask "visual-studio-code-insiders"
cask "vlc"
cask "webstorm"
cask "yed"
cask "zulu"
mas "GoodNotes", id: 1444383602
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Ora", id: 1340501510
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
